### ISSUE TITLE
Deleted object not saving to iCloud

### ISSUE THREAD

**Issue by noecantu** [deeje/CloudCore#10]
I've tried and tried but have not had any luck saving deleted object to iCloud. Everything else works fine. I have looked at the example repeatedly with no luck. I am trying to delete as shown below:

    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle,    forRowAt indexPath: IndexPath) {
        let anObject = fetchedResultsController.object(at: indexPath)
        let objectID = anObject.objectID
        if editingStyle == .delete {
            persistentContainer.performBackgroundTask { (moc) in
                moc.name = CloudCore.config.pushContextName
                if let objectToDelete = try? moc.existingObject(with: objectID) {
                    moc.delete(objectToDelete)
                    try? moc.save()
                }
            }
            print("In editingStyle == .delete.")
        }//End if editingStyle
    } //End tableview editingStyle

I have also tried:

    func tableView(_ tableView: UITableView, commit editingStyle: UITableViewCell.EditingStyle, forRowAt indexPath: IndexPath) {
        if editingStyle == .delete {
            // Fetch Bullets
            let bullets = fetchedResultsController.object(at: indexPath)
            // Delete Bullets
            bullets.managedObjectContext?.delete(bullets)
            print("In editingStyle == .delete.")
        }//End if editingStyle
    } //End tableview editingStyle

And save here:

    func controllerDidChangeContent(_ controller: NSFetchedResultsController<NSFetchRequestResult>) {
        tableView.endUpdates()
        persistentContainer.performBackgroundTask { moc in
            moc.name = CloudCore.config.pushContextName
            try? moc.save()
            print("Saving to CoreData from controllerDidChangeContent...")
        }
        tableView.reloadData()
        updateView()
    }//End controllerDidChangeContent

Please help. I'm not sure what I am doing wrong.

**Comment by deeje** [comment]
What happens with each of these code paths?

in the first case, is there a FetchedResultsController driving updates to your tableView?

In the second, I don't think its a good use of FetchedResultsControllers to drive more changes, seems like a potential recursive experience.  I implement the first case in all my apps.

**Comment by noecantu** [comment]
I'm currently using the first case with the following.

    let managedObjectContext = persistentContainer.viewContext
    // MARK: Results
    fileprivate lazy var fetchedResultsController: NSFetchedResultsController<Bullets> = {
        //Create Fetch Request
        let fetchRequest: NSFetchRequest<Bullets> = Bullets.fetchRequest()
        // Configure Fetch Request
        fetchRequest.sortDescriptors = [NSSortDescriptor(key: #keyPath(Bullets.caliber), ascending: true, selector: #selector(NSString.localizedStandardCompare(_:))), NSSortDescriptor(key: #keyPath(Bullets.brand), ascending: true), NSSortDescriptor(key: #keyPath(Bullets.weight), ascending: true, selector: #selector(NSString.localizedStandardCompare(_:))), NSSortDescriptor(key: #keyPath(Bullets.type), ascending: true)]
        // Create Fetched Results Controller
        let fetchedResultsController = NSFetchedResultsController(fetchRequest: fetchRequest, managedObjectContext: managedObjectContext, sectionNameKeyPath: #keyPath(Bullets.caliber), cacheName: nil)
        // Configure Fetched Results Controller
        fetchedResultsController.delegate = self
        return fetchedResultsController
    }() //End fetchedResultsController

As mentioned before, everything works fine, locally (CoreData). Objects are added and deleted with persistence. I can also add objects, update objects, and push them to iCloud on launch. I am not having any luck with the local deletion of objects syncing with iCloud.

**Comment by deeje** [comment]
Are you using NSPersistentHistory?  If yes, have you properly configured the the CloudCore "recordName" property in your Core Data Schema with "Preserve After Deletion" enabled?

<img width="707" alt="Screen Shot 2019-05-16 at 09 51 18" src="https://user-images.githubusercontent.com/118052/57872339-51b8c300-77c0-11e9-90d6-7006c307277a.png">

**Comment by noecantu** [comment]
Aha!!! That was it! Thank you so much for your help!

**Comment by intonarumori** [comment]
@deeje Can you please elaborate on the `Preserve After Deletion` requirement on the `recordName` field?
The readme doesn't mention it and would be great to have it clarified.

Thanks.

**Comment by deeje** [comment]
CloudCore supports asynchronous synchronization, which means that changes are queued to be pushed up to CloudKit.  In NSPersistentHistoryTracking, when records are deleted, you can indicate which subset of fields get copied into the history record itself.  We need the recordName field to be preserved, such that when we propagate the delete into CloudKit, we can indicate which record to delete.
