### ISSUE TITLE
After Deleting Documents and Data

### ISSUE THREAD

**Issue by JayStory4u** [deeje/CloudCore#11]
After user delete documents and data on settings of iPhone, CloudCore does not operate synchronization.

**Comment by deeje** [comment]
Can you restate the issue?  A good issue report includes
- Description of issue
- steps to reproduce
- expected results
- actual results

**Comment by dippnerd** [comment]
I think this is the same thing I'm running into. I do a delete:
```
moc.delete(objectToDelete)
try? moc.save()
```
and it deletes from Core Data, but I don't get any logs about CloudCore deleting, and the records are still in CloudKit dashboard.

**Comment by noecantu** [comment]
Check this answer. It helped me:

https://github.com/deeje/CloudCore/issues/10#issuecomment-493147461

**Comment by dippnerd** [comment]
bingo, that did it! thank you!!
