### ISSUE TITLE
Switching both organization and employee to public in example fails on employee

### ISSUE THREAD

**Issue by Cyclic** [deeje/CloudCore#18]
Unfortunately everything was working great in the example when using private scope, but once I switched to public scope, resetting the development environment first, the employee no longer saves and errors are displayed. I'm happing to dig in on some debugging if you can point me in the right direction:

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/553800/83318715-226acd80-a1ec-11ea-996a-ded7369178bf.png">

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/553800/83318720-30205300-a1ec-11ea-9ffd-84fda5c8a869.png">

<img width="824" alt="image" src="https://user-images.githubusercontent.com/553800/83318729-46c6aa00-a1ec-11ea-87c0-5206c8ac026c.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/553800/83318733-4cbc8b00-a1ec-11ea-99fd-270307ae209c.png">

<img width="767" alt="image" src="https://user-images.githubusercontent.com/553800/83318742-61991e80-a1ec-11ea-9550-a356a16de41e.png">

<img width="792" alt="image" src="https://user-images.githubusercontent.com/553800/83318746-678eff80-a1ec-11ea-8fdf-d5e57ec66637.png">

<img width="1593" alt="image" src="https://user-images.githubusercontent.com/553800/83318752-82fa0a80-a1ec-11ea-8bea-a7574b965edf.png">

Clicking on the record for an employee in the CloudKit Dashboard yields the following error:
<img width="610" alt="image" src="https://user-images.githubusercontent.com/553800/83318760-a4f38d00-a1ec-11ea-8e3d-de7e327ff543.png">

**Comment by Cyclic** [comment]
UPDATE: I discovered that removing the "public" property from the employee entity got the employees syncing.

**Comment by deeje** [comment]
Hmm, just a hunch… the parent-child relationship is there so that private records can be shared properly.  If you're moving certain classes to public, you may not need the parent-child relationship.  fwiw
